apiVersion: v1
kind: PersistentVolume
metadata:
  name: basic-volume
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/jilles/data/projects/workshop/volumes"