apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: mysql-claim
      containers:
        - name: mysql
          image: mysql:5.7.38
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 400Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-storage
          # envFrom:
          #   - secretRef:
          #       name: mysql-secrets
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          ports:
            - containerPort: 3306
              name: mysql
