apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: database
  name: mysql-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi